### ISSUE TITLE
As a project manager, I would like to set up the CI pipeline for the A22 traffic data sensors DC developed by Davide Montesin with Chris Mair

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#101]
Deployment and setup of 2 separate applications is needed:
- [x] data importer written by Chris M. 
- [x] data elaboration data collector by Davide M.

**Comment by bertolla** [comment]
Waiting for a pull request by Davide M. Already  sent an email where I explained how we expect code

**Comment by rcavaliere** [comment]
@bertolla Chris has provided his contribution, so we can proceed with this issue

**Comment by rcavaliere** [comment]
@bertolla Chris has found a bug in the data stream provided from A22, which now should be fixed (we are still waiting for A22 for providing more explanations). Chris wants to wait some days to check that the problem has been solved. Please check with Chris if everything is fine, if yes please proceed with the integration in the testing environment

**Comment by bertolla** [comment]
Chris M. is still analyzing the data and found further problems. He documented it and explained it in his last mail. Maybe we should attach it to the project informations.

**Comment by rcavaliere** [comment]
@bertolla completed data check in the testing DB. Everything seems OK
When going onto production, remember to change the property file (where is it in this repository?) so that in the station table in the DB we have:
- origin = A22 (now void)
**- stationtype = TrafficSensor (now a22-traffic)**
The second one is particularly important so that this dataset is available through our API together with the dataset of the Municipality of Bolzano
