### ISSUE TITLE
As a project manager, I would like to set up the CI pipeline for the A22 Variable Message Signs (VMS) DC developed by Davide Montesin with Chris Mair

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#102]

**Comment by bertolla** [comment]
Informed Davide M. how to do pull-request. Now on standby waiting for his pull-request.

**Comment by rcavaliere** [comment]
@bertolla Davide has sent his update. Please check with him the open point related to the retrieval of the last record in the ODH

**Comment by bertolla** [comment]
@rcavaliere 
I created a CI and a test deployment pipeline but I'm missing:
- [ ] credentials for testing env(please send them through an encrypted email with office365)
- [ ] README with a basic documentation
- [ ] any type of unit/integration test

**Comment by rcavaliere** [comment]
@bertolla credentials sent (please confirm)

**Comment by bertolla** [comment]
I got them but I'm still missing the endpoint, which means I need an URL

**Comment by rcavaliere** [comment]
http://webservices.cau-a22.org:8080/ valid for all A22 Data Collectors developed by Chris and Davide (not for innovative air quality sensors)

**Comment by bertolla** [comment]
No ssl url?

**Comment by rcavaliere** [comment]
No...

**Comment by bertolla** [comment]
Deployed the datacollector to testing environment. It seems to not insert data, I'll wait for documentation so I won't loose time. This is the log i get:
```
[localhost-startStop-1] INFO  it.bz.noi.a22.vms.A22Scheduler  - Start A22Scheduler
[localhost-startStop-1] INFO  it.bz.noi.a22.vms.A22Scheduler  - Start A22Scheduler
[DefaultQuartzScheduler_Worker-1] INFO  it.bz.noi.a22.vms.MainA22Sign  - Start A22SignMain
[DefaultQuartzScheduler_Worker-1] DEBUG org.apache.commons.configuration.PropertiesConfiguration  - FileName set to application.properties
[DefaultQuartzScheduler_Worker-1] DEBUG org.apache.commons.configuration.ConfigurationUtils  - ConfigurationUtils.locate(): base is null, name is application.properties
[DefaultQuartzScheduler_Worker-1] DEBUG org.apache.commons.configuration.DefaultFileSystem  - Could not locate file application.properties at null: no protocol: application.properties
[DefaultQuartzScheduler_Worker-1] DEBUG org.apache.commons.configuration.ConfigurationUtils  - Loading configuration from the context classpath (application.properties)
[DefaultQuartzScheduler_Worker-1] DEBUG org.apache.commons.configuration.PropertiesConfiguration  - Base path set to jar:file:/var/lib/tomcat8/webapps/dc-vms-a22/WEB-INF/lib/dc-interface-2.1.0.jar!/application.properties
[DefaultQuartzScheduler_Worker-1] DEBUG it.bz.noi.a22.vms.MainA22Sign  - elaboration time (millis): 675
```

**Comment by bertolla** [comment]
Data is entering now but there are still things Davide will adjust, so I will wait for his next pull-request

**Comment by rcavaliere** [comment]
@bertolla, yes, David will also change something in the way data are provided to the bdp-core. Please push him if he does not make a push in a few days... Once the new pull request is available, please update it in the testing environment

**Comment by rcavaliere** [comment]
Checked the data in the testing environment. For me it is OK, let's go in production with this DC.
