### ISSUE TITLE
As a project manager, I would like that the Bluetooth / travel times elaboration chain is compatible with bdp-core-v2 and are visible again on analytics (including new stations) - implementation by Davide Montesin

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#103]

**Comment by bertolla** [comment]
Waiting for Davide to provide new code

**Comment by rcavaliere** [comment]
@bertolla did you manage to fix the problems with Davide's code in relation with the integration tests? Please contact him if necessary and proceed with deployment in testing environment

**Comment by bertolla** [comment]
application is running on testserver. We only got bluetooth records till april there.
Seems to be working correctly: http://tomcat.testingmachine.eu/bluetoothtrafficelaboration/

**Comment by rcavaliere** [comment]
Elaborations tested, seem to work fine. Asked Davide to change elaborations' period and to add two data types, waiting for feedback

**Comment by bertolla** [comment]
@rcavaliere 
I tried to add a new row in scheduler_task but it's not working. Furthermore I deployed the app on the testserver and it is calculating data which it already calculated and inserting nothing in the database.
We miss any kind of written documentation on this, like we don't know how to insert new elaborations and how to read a situation like this. Maybe you know better. Check out: http://tomcat.testingmachine.eu/bluetoothtrafficelaboration/

**Comment by bertolla** [comment]
@rcavaliere 
Elaborations are being calculated but are quiet slow because it hast to calculate the last months.
You can see the progress here: http://99.81.159.57:8080/bluetoothtrafficelaboration/

**Comment by rcavaliere** [comment]
@bertolla @Piiit please notify me when the links are configured as discussed (only active links should be ACTIVE) and the new elaborations related to the new periods are ongoing.

**Comment by bertolla** [comment]
@rcavaliere Peter created the missing links. Elaborations are being calculated at the moment, but it will take time since it has to create the whole history. You can see the progress on the same link as before

**Comment by rcavaliere** [comment]
@bertolla @piit if I am right our API does not expose anything for the LinkStations, and that's why we can't see anything on the analytics webapp. Can you please check this? In these days a lot of new boxes have been installed and it would be nice to see all the data entering and the new elaborations

**Comment by rcavaliere** [comment]
@bertolla I also see that for the Bluetooth elaborations we still not have the elaborations with new periods. Are they running correctly?

**Comment by rcavaliere** [comment]
@bertolla please ask if you do not remember exactly the periods for the new elaborations to be created. I can prepare here the exact list of new elaborations to be added. If we still miss documentation from David on how to do that, please ask / push him.

**Comment by rcavaliere** [comment]
@bertolla please also remember to put in production the last version of the analytics web-app, so that I can check all new functionalities developed by Davide

**Comment by rcavaliere** [comment]
@bertolla we are still missing the new elaborations in order to close this issue. The new elaborations are the following:
-[] count_bluetooth_intime (args 600)
-[] count_bluetooth_intime (args 3600)
-[] count_match_intime (args 600)
-[] count_match_intime (args 3600)
-[] run_mode_intime (args 600)
-[] run_mode_intime (args 3600)
-[] run_mode_intime (args 3600)
-[] compute_bspeed (args 600)
-[] compute_bspeed (args 3600)
Did Davide provide you all documentation to add new elaborations alone? In this way we can also take the opportunity to verify if the documentation is OK.

**Comment by rcavaliere** [comment]
@bertolla I have seen another issue. Our API does not provide the results of the elaborations associated to the data type "velocita'". But it seems to me that the elaborations are correctly executed. Can you please check this?

**Comment by bertolla** [comment]
> Did Davide provide you all documentation to add new elaborations alone?
I'm still missing documentation. 

> @bertolla I have seen another issue. Our API does not provide the results of the elaborations associated to the data type "velocita'". But it seems to me that the elaborations are correctly executed. Can you please check this?
What do you mean with API? It is in the database but you can't see it on analytics?
Is that the case?

**Comment by rcavaliere** [comment]
OK, I will ask Davide for the documentation. 
Regarding the API, I mean our API: http://ipchannels.integreen-life.bz.it/origin-destination/swagger-ui.html

**Comment by bertolla** [comment]
@rcavaliere 
The first geometries of the links are already stored correctly in the database. To use it for the length retrieval this querry has to be integrated in the bspeed elaboration sql file:
``` sql
select s.stationcode,ST_LENGTH(ST_Transform(linegeometry,25832)) from edge e join station s on e.edge_data_id = s.id
```
I think Davide knows where to put the hands to make this work.

**Comment by bertolla** [comment]
Importer is up and running. Refer here for documentation: https://github.com/noi-techpark/bdp-elaborations/tree/master/ShapefileFeatureImporter
