### ISSUE TITLE
As a project manager, I would like that the CI for the new realtimebus server + new mobility.meran.eu/bus prototype are set-up (implementation by Daniel Rampanelli)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#104]

**Comment by bertolla** [comment]
server is up and running on https://realtimebusv2.sasabus.org/
Examples:
https://realtimebusv2.sasabus.org/vdv/list
https://realtimebusv2.sasabus.org/v2/stops
https://realtimebusv2.sasabus.org/v2/routes/221/4//geometry.geojson

We are missing 2 things in my opionon:
- tests (0 test coverage)
- API documetation

**Comment by bertolla** [comment]
I modified the old php version, so it sends the data to the new endpoint and therefore the realtime data can be seen here as json:
- https://realtimebusv2.sasabus.org/app/realtime/delays
- https://realtimebusv2.sasabus.org/app/realtime

**Comment by bertolla** [comment]
@rcavaliere 
Daniel Rampanelli told me that there is  a Swagger documentation, which in my opinion isn't working properly yet. I informed him and waiting for his response. If you want to you can already test the endpoints described in my previous comments.

**Comment by rcavaliere** [comment]
Status: Daniel Rampanelli has to fix the system, since on the client we don't see static and real-time data (they just appear sometimes)

**Comment by bertolla** [comment]
I would close this userstory since CI is setup since  a while now ant the software is currently just failing in part, because of SASA providing bad dataquality(as said by D.R.)

**Comment by rcavaliere** [comment]
@bertolla as agreed during the meeting this Monday with SASA and Daniel, please coordinate the merge of the two contributions from Daniel and SASA, so that we can put in test mode a consolidate version of realtimebus. Please also provide SASA all access credentials so that they can test the connection with their new APP.

**Comment by rcavaliere** [comment]
@bertolla please test the new pull requests that have been made available by Daniel R.

**Comment by bertolla** [comment]
Integrated latest pull-requests and after doing some fixing disucussed in noi-techpark/realtimebus-v2/issues/10 noi-techpark/realtimebus-v2/issues/9 it finally works.You can try it by using the webcomponent https://webcomponents.opendatahub.bz.it/webcomponent/7620f04d-ed08-4770-bbda-dfe959ae078e or doing requests on the endpoint directly.
https://realtimebusv2.sasabus.org/v2/docs

**Comment by rcavaliere** [comment]
@bertolla @ohnewein 
Finally! The web-component still suffers of some unproper mapping of the routes. Try the full screen version here: 

[](data:text/html;charset:utf8,<html><head><title>MyWebComponent</title></head><body><smart-mobility endpoint="https://realtimebusv2.sasabus.org" routes="^.*$"></smart-mobility><script src="https://cdn.webcomponents.opendatahub.bz.it/dist/7620f04d-ed08-4770-bbda-dfe959ae078e/v1.0.3/smartmobility.min.js"></script>)

I need to manage this with Daniel. Otherwise we have to find a way to solve this issue, by collecting all necessary information on how we can handle this without his support.

For the API, I suggest to ask SASA to test it through their new APP version.

**Comment by rcavaliere** [comment]
For the testing, I would like to wait that the last paths are corrected by Daniel. There is also a further improvement regarding the interpolation of real-time bus positions made by SASA to be integrated. Let's wait this week before taking other actions.

**Comment by rcavaliere** [comment]
A week has passed without any action. Daniel has confirmed he is working on this... let's push him with the invoicing incentive :-)

**Comment by rcavaliere** [comment]
Still missing:
-  [ ] paths fixing
-  [ ] realtime positions interpolation (improvement SASA, instructions to be given)

**Comment by bertolla** [comment]
pulled in pull request and aplied to test server
