### ISSUE TITLE
As a project manager, I would like that the CI for the meteo DC is set-up (new DC for the open data of the Province of Bolzano, developed by EDP)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#105]
- [x] ci pipeline
- [x] testing pipeline
- [x] check if data enters smoothly

**Comment by bertolla** [comment]
CI and testing pipeline are up and running, but we have a bug: https://github.com/noi-techpark/bdp-commons/issues/107

**Comment by bertolla** [comment]
@rcavaliere The datacollector is now running and data is being put in the test database.
I noticed that the new types didn't get inserted(e.g. foliar-wetting). Could there be a plausible reason?

**Comment by rcavaliere** [comment]
@bertolla wonderful! I will test and check this.

**Comment by rcavaliere** [comment]
@bertolla I see some major issues in the data modelling. We need a modification by EDP. The major problem is that a control of current stations already saved in the database is not performed, and stations with same stationcode have now two records in the station table. This should be fixed and then we can make further tests.

**Comment by rcavaliere** [comment]
Problem seems to be solved, I suggest to go into production
