### ISSUE TITLE
As a meteorological data analyst, I would like that all measurements of the meteo stations in the Province of Bolzano are correctly retrieved. Some measurements are up-to-date, even if data exposed by the API are available.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#128]

**Comment by bertolla** [comment]
@rcavaliere 
Finally understood the reason for this malfunctioning. 
There are holes in the datasets provided by the province. Right now the tool always only requests data of one day to avoid out of memory issues. But if the station did not provide data for more than 24 hours the call will never return any data. If we increase the interval we would probably solve the problem, risking out of memory problems but the problem itself is still here.
In the end the datacollector algorithm is not adapted perfectly and so this case fails.
Are we asking Marco to fix this or have you got any Ideas?

**Comment by rcavaliere** [comment]
@bertolla if this is just a logic change I would suggest to do it by our own, increasing from 24 hours to 7 days. Can you do that?

**Comment by bertolla** [comment]
Additionaly I noticed that last record is requested by using a static period, while the period varies by datatype and therefore same window is getting requested again and again for some types

**Comment by rcavaliere** [comment]
Let's avoid to consider the period in this logic

**Comment by bertolla** [comment]
OK implemented it now most of datasets are up to date. The only once which are not updating are the following:
```
            cname             |            name             
------------------------------+-----------------------------
 air-humidity                 | Senales Croda d. Cornacchie
 air-humidity                 | Solda Cima Beltovo
 air-temperature              | Senales Croda d. Cornacchie
 atmospheric-pressure         | Bolzano
 atmospheric-pressure         | Laimburg
 atmospheric-pressure         | Lasa - Oris
 atmospheric-pressure-reduced | Alpe di Siusi Zallinger
 atmospheric-pressure-reduced | Plose
 BN                           | Laimburg
 BT.010                       | Lasa - Oris
 BT.025                       | Laimburg
 BT.050                       | Laimburg
 BT.050                       | Lasa - Oris
 LT.050                       | Laimburg
 LT.050                       | Lasa - Oris
 rainfall-duration            | Bolzano
 snow-level                   | Alpe di Siusi Zallinger
 SSTF                         | ADIGE A PONTE ADIGE
 SSTF                         | ADIGE A SALORNO
 TD                           | Laimburg
 TD                           | Lasa - Oris
 U.W.ABST                     | Laimburg
 water-level                  | Lago di Braies
 water-level                  | Lago Grande di Monticolo
 water-temperature            | Lago di Braies
 water-temperature            | Lago Grande di Monticolo
 WR.BOE                       | Laimburg
 WR.BOE                       | Lasa - Oris
 Z.BOE                        | Laimburg
 Z.BOE                        | Lasa - Oris
(30 rows)
```

**Comment by rcavaliere** [comment]
Works but there is some issues with the authentication side (e.g. VMS data are not visible)
