### ISSUE TITLE
As a traffic expert, I would like to test the push mechanism of the pilot system managing the on-spot parking sensors in Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#132]
We have decided to use as generic URL logger.testingmachine.EU

- [x] set up the Apache and activate the URL

**Comment by bertolla** [comment]
Data can be send to http://logger.testingmachine.eu/. 
For testing i did not enable ssl. but should work the same.
What kind of data will they send?

**Comment by rcavaliere** [comment]
Wonderful, I have shared the end-point with the data provider. The data will relate to the position of the parking lots and their current occupancy (free / occupied). Let's how they are structured.

**Comment by rcavaliere** [comment]
Data are entering. Message example:

{
"devEUI":"001bc50670100539",
"appEUI":"70b3d59b60000003",
"fPort":1,
"gatewayCount":1,
"rssi":-51,
"data":"gAAAAyIQ8/kBAAAD1FY6ADUAABWZAMk6",
"parsedData":{
	"FW-version":58,
	"Magnitude":980,
	"Payload":"KEEPALIVE",
	"Progtx":5529,
	"Retries":0,
	"Rssi":53,
	"Sensor-address":"00000322",
	"Status":"free"},
"loRaSNR":10.8,
"frequency":868100000,
"dataRate"{
	"modulation":"LORA",
	"spreadFactor":12,
	"bandwidth":125},
"devAddr":"e8a0b67e",
"fCntUp":1,
"time":"2019-10-08T06:16:14.385035347Z",
"encrypted":false,
"format":"base64",
"gateways":[{
	"mac":"00800000a0004693",
	"time":"0001-01-01T00:00:00Z",
	"timestamp":3625854332,
	"frequency":868100000,
	"channel":0,
	"rfChain":1,
	"crcStatus":1,
	"codeRate":"4/5",
	"rssi":-51,
	"loRaSNR":10.8,
	"size":37,
	"dataRate":{
		"modulation":"LORA",
		"spreadFactor":12,
		"bandwidth":125}
}]
}
