### ISSUE TITLE
As a traffic analyist, I would like to check wheter A22 Traffic DC is working properly

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#137]

**Comment by bertolla** [comment]
last elaboration has been done on 16/10

**Comment by rcavaliere** [comment]
That is not good. Can you check the problem here or eventually try to relaunch the data collector?

**Comment by bertolla** [comment]
a22 db is uptodate and not logging any error. a22 trafficelaborations are also not logging errors

**Comment by rcavaliere** [comment]
Strange. Have you tried to relaunch the data collector? How is the chron currently configured?

**Comment by bertolla** [comment]
I did just now but I do not think it will work. It starts every half hour

**Comment by rcavaliere** [comment]
Please check if something happens after this restart. If not, let's involve Davide + Chris to check what is wrong...

**Comment by bertolla** [comment]
works again

**Comment by bertolla** [comment]
Now the newest timestamp is 2019-10-21 14:00:00 but it's not changing. To me it seems something is not working with the scheduling which is not refletcted in the log files.
I think we should involve Davide, since it's his part

**Comment by bertolla** [comment]
by digging deeper I noticed that there is a station which is not up to date with the rest (SEZIONE DI RILEVAMENTO KM.  87,8 - BOLZANO SUD (corsia di sorpasso sud, direzione sud))
And by setting the log file to debug I saw that exactly this elaboration where being calculated. Which means the behavior is the following. Bring every station up to date and do not schedule any othere tasks before it's finished. I would suggest to wait till the elaborations are up to date again to see if it's true. The disadvantage of this approach is that if a new station is added, no new elaborations of the other stations will be added as long as the elaboration of the one which is missing history hasn't finished.

**Comment by rcavaliere** [comment]
@bertolla ah ok, that's was the issue. But why wasn't it considered before? Let's wait and see what happens when all stations are aligned. Thanks for your deep logging analysis work!

**Comment by bertolla** [comment]
As soon as the calculation finished the next station (SEZIONE DI RILEVAMENTO KM. 103+700 - EGNA ORA (corsia di sorpasso nord, direzione nord) )started to calculate elaborations from January 2017. For every station it takes days to complete. Is that normal?

**Comment by rcavaliere** [comment]
It depends if there are already elaborations stored in the DB. If not, it is normal. If yes, no. Can you check this?

**Comment by bertolla** [comment]
As we discovered the history elaboration import will take a long time and therefore this is not really a bug but more like an algorithm which takes time. I switched to a faster ec2 instanz to make elaborations faster but it still will take ~ 2 months to calculate all elaborations.

**Comment by rcavaliere** [comment]
@bertolla let's close this issue for now but please check regularly if the DC is working fine and new elaborations are entering in the DB. I will check this too on the analytics, once properly working.
