### ISSUE TITLE
As a bike sharing user I would like to see the real-time bike sharing data of the service in Merano integrated in the ODH

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#142]
EDP has completed the development work. The issue is related to the creation of the CI pipeline and the integration in our testing / production environment
See https://github.com/noi-techpark/bdp-commons/pull/141

**Comment by bertolla** [comment]
@rcavaliere 
Following the documentation I need to set these 2 parameters
app.auth.token=Bearer AUTH_TOKEN
app.auth.selectedTeam=SELECTED_TEAM

Can you provide them in an encrypted mail?
Thx

**Comment by rcavaliere** [comment]
Done, please let me know if it works correctly.

**Comment by bertolla** [comment]
ok I'm missing the second configuration parameter, which in documentation are stated as
> #Authorization Token and SelectedTeam, this variables must be injected
If you do not know about it, better ask Marco so he can also explain it

**Comment by rcavaliere** [comment]
Try with the code I just sent you

**Comment by bertolla** [comment]
Application deployed on test server. Check the test database if data enters correctly

**Comment by rcavaliere** [comment]
@bertolla still don't see the data related to the data collector, did you activate it again?

**Comment by rcavaliere** [comment]
@bertolla the DC works fine please go into production
