### ISSUE TITLE
[bikesharing-bz] Clarification for data types and data transformation in bikesharing-bz Data Collactor

### ISSUE THREAD

**Issue by edp-progetti** [noi-techpark/bdp-commons#145]
I implemented the transformation of data coming from Ecospazio web services as described in the analysis document. There was a point to discuss about the metadata to attach to the Stations of type "Bicyclestation" (the type "spots_avalilability" filled from field "free_bays" of the web service). In fact the web service gives three values: total_bays, free_bays, available_vehicles and in some cases, if a bay or a bike is out of order, total_bays != free_bays + available_vehicles.
I summarize here the way I implemented the transformation to check if it is correct:

"Bicyclestation" (first level):
- Measurements:
  - "availability" (takes value from "state" web service attribute, has values like "READY", "OUT_OF_SERVICE"...)
  - "number-available" (takes value from attribute "availableVehicles", integer, the number of bikes currently available in that station)
  - "free-bays" (takes value from attribute "freeBays", integer, the number of free bays ready to accept a bike return)
  - "total-bays" (takes value from attribute "totalBays", integer, the number of bays present in that station) TotalBays can be different from the sum of numberAvailable + freeBays becouse some bay could be out of service.

"Bicyclestationbay" (second level):
- Measurements:
  - "availability" (takes value from "state" web service attribute, has values like "READY", "OUT_OF_SERVICE"...).
  - "usage-state" (takes value from "usageState" web service attribute, has values like "PRELIEVO", "RICONSEGNA". In case of an empty string we do not store the value because the Open Data Hub does not permit to set a value as ampty string).

"Bicycle" (third level):
- Measurements:
  - "availability" ("1" if the bike is parked in a bay, if the bike is in use the measurement is not stored because the web service does not give information about this bike).
  - "battery-state" (takes value from "batteryState" web service attribute, has values like "CHARGED", "CHARGING". if the bike is in use the measurement is not stored because the web service does not give information about this bike).

**Comment by rcavaliere** [comment]
@edp-progetti You are right, we must consider an additional type for the Bicyclestation (better, BikeSharingStation, using the naming of the station types we have). I have uploaded a new version of the specification containing this modification. I also noticed and integrated the different typing of the types name, which is OK - thanks for this!
