### ISSUE TITLE
As a user, I would like to see the real-time data of the new bike sharing service in Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#146]
EDP has implemented the prototype version of the DC, which should be integrated in the testing environment so to be tested.

**Comment by bertolla** [comment]
CI is failing. I informed Marco through the pull-request

**Comment by bertolla** [comment]
Set the application in the test environement. Data should already be available in test db.

**Comment by rcavaliere** [comment]
@bertolla, as already shared also with EDP, I don't see data stored in the measurement table for the stationtype = Bicyclestationbay or stationtype = Bicycle. Can you please share some log files to understand why is happening this?

**Comment by bertolla** [comment]
measurementstring contains that data

**Comment by rcavaliere** [comment]
yes, you are right, that's what the point... everything works fine, we can put the DC in production!
