### ISSUE TITLE
As a user I would like to see the real-time on-spot parking data of the city of Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#149]
Done by EDP [in 1 sprint]. The task is to create the CI pipeline in the ODH environment by integrating the pull request that is made available by the supplier.

**Comment by bertolla** [comment]
The app is up and running on our testenvironment. Station and datatypes can be found in the test db.
Records can be pushed through a post to:
https://tomcatsec.testingmachine.eu/dc-onstreet-parking-bz/json/pushRecords

To make it work on the test environment with our newest bdp-core and make it buildable in a docker env I had to make these changes: 1c7cd91cd96319b98897357542742c4b347fbb5e 974a7811f2afca6dc7b3f1ccd512abae972275de

**Comment by rcavaliere** [comment]
@bertolla, wonderful. I will provide the URL to the data provider and see if the data flow works properly.

**Comment by rcavaliere** [comment]
Data provider must reconfigure the end-point of the push service, otherwise we don't see data entering. Request sent on March 11st.

**Comment by rcavaliere** [comment]
Still no feedback here, I guess to the Coronavirus emergency. I will make another try, otherwise I am afraid that we have to put in the backlog (or leave it for a while in the testing lane...)

**Comment by Piiit** [comment]
@rcavaliere @bertolla Please provide some information on how to test this... Thank you

**Comment by rcavaliere** [comment]
I don't know why I assigned you... it's my task, currently it's blocked.

**Comment by Piiit** [comment]
Aha... ok. Thx

**Comment by rcavaliere** [comment]
@bertolla, the data provider should now send the data in push mode to the testing environment. I see in the test DB the metadata data (tables station / metadata) but no realtimevalues. Could you please check if we are receiving data correctly?

**Comment by bertolla** [comment]
@rcavaliere 
the app is now deployed on production and has already synched stations and types but we need to specify a production endpoint for the realtime data and communicate it to the data provider.
I thought about something like:
https://parking.opendatahub.bz.it/dc-onstreet-parking-bz/json/pushRecords
But maybe you have a better idea for a subdomatin?
Cheers,
Patrick

**Comment by rcavaliere** [comment]
@bertolla for me it is fine. Let me know if it is OK for you, I will communicate it to the data provider

**Comment by bertolla** [comment]
ok this should be working now

**Comment by rcavaliere** [comment]
Data Provider is now sending data to the production end point. @bertolla can you confirm me that data is entering in the production environment?

**Comment by bertolla** [comment]
Yes you can check with this query
``` sql
select * from measurement where station_id in (select id from station where stationtype='ParkingSensor');
```
