### ISSUE TITLE
App Developer want API access to Covid-19 data

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/bdp-commons#153]
Can we answer to the Data Access request in this tweet?

https://twitter.com/bmgnrs/status/1242802473791881216

**Comment by bertolla** [comment]
Data is now in bdp and can be used through v2.
Example: https://mobility.api.opendatahub.bz.it/v2/api/flat/Covid-19/*?limit=200&offset=0&shownull=false&distinct=true (Not a history call just latest values)
To see where are cases of Corona or/and people in isolation it can already be seen on webcomponent:
```
data:text/html;charset:utf8,<map-widget domain="mobility" station-types="Covid-19"></map-widget> <script src="https://cdn.webcomponents.opendatahub.bz.it/dist/8d194fde-5061-4257-9580-56eb0aef4cef/v0.3.4/map_widget.min.js"></script>
```

**Comment by ohnewein** [comment]
I have tested the web component map. It looks great!
