### ISSUE TITLE
As manager of the Centro Trevi and the DRIN I want events that I organize to be published as Open Data in the Open data hub.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-commons#156]
The task list are:
- [x] create a google spreadsheet for the event information
- [x] implement the data collector to insert the data in the Open Data Hub
- [x] implement a web service that distributes the information

**Comment by sseppi** [comment]
The moment in which the spreadsheet is changed, data should be visible on https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true&shownull=false&distinct=true

**Comment by RudiThoeni** [comment]
I see here 2 different data types with different structures.... Is it possible to change the query in order to get only events?

**Comment by RudiThoeni** [comment]
wrong issue continued here https://github.com/noi-techpark/odh-alpinebits-destination-data-server/issues/14
