### ISSUE TITLE
As a manager of Centro Trevi I want the daily suggestions to be published as open data through the Open Data Hub in order to maximize their visibility

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-commons#157]
The task list are:
- [x] create a google spreadsheet for the event information
- [x] ask if the suggestion has to be associated to a specific location or not
- [ ] implement the data collector that stores the data in the Open Data Hub
- [ ] implement a web service that distributes the information

**Comment by ohnewein** [comment]
original issue, now there are smaller issues created from this one.
