### ISSUE TITLE
As a manager of Centro Trevi I want the location (places and rooms) of Centro Trevi and DRIN to be published as open data through the Open Data Hub in order to maximize their visibility

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-commons#171]

**Comment by bertolla** [comment]
The moment in which the spreadsheet is changed, data should be visible on https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true&shownull=false&distinct=true and
https://mobility.api.opendatahub.testingmachine.eu/flat/Culture/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true&shownull=false&distinct=true

**Comment by sseppi** [comment]
@bertolla it seems tht the syncronization between the spreadsheet and the ninja API doen't work anymore.

**Comment by bertolla** [comment]
@sseppi Seems to work now. Test it with these 2 calls by changing the spreadsheet and check if it reflects the changes:
- https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/*/latest?limit=-1&select=tmetadata,mvalue&shownull=true&distinct=true
- https://mobility.api.opendatahub.testingmachine.eu/v2/flat/Culture/?where=sactive.eq.true&distinct=true

**Comment by sseppi** [comment]
@bertolla I've tested and the update is now working fine but I've seen that the import of dates and times seems not work properly.
It seems that the collector imports only the firt number of the date and/or time (eg. the date 01/01/2020 is imported as 01 and the time 16:00:00 is imported as 16). Is that right or do I miss something?

**Comment by bertolla** [comment]
Si c'era un altro baco nel parsing di numeri, risolto e gia messo in produzione: https://mobility.api.opendatahub.bz.it/v2/flat/Culture/*/?limit=-1&offset=0&select=tmetadata&where=sactive.eq.true&shownull=false&distinct=true

**Comment by sseppi** [comment]
OK! Now seems to work fine!
Thanks
