### ISSUE TITLE
maps.noi.bz.it backend: problem with add/remove column in backend spreadsheet

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-commons#181]
If I add or remove a column in a spreadsheet of the back-end of maps.noi.bz.it the API returns the inserted data in the wrong position. For example if I remove the blank column in the "Selettori Group" sheet the following call:

https://mobility.api.opendatahub.bz.it/v2/flat/NOI-Place/*/latest?limit=-1&select=tmetadata,mvalue&shownull=true&distinct=true

retrieves the data in the wrong position (e.g. the language aren't in the right position).

As a data maintainer I want to be able to add and remove the columns without changing the position of the data retrieved in the API.

**Comment by bertolla** [comment]
This is a bug i discovered recently while developing for centro trevi. On testing it should be fixed for ct and as soon as I have my worklaptop again I will also deploy the changes for maps

**Comment by sseppi** [comment]
We need to finish the new dockerization before to publish this feature.

**Comment by bertolla** [comment]
@sseppi You can test if your changes correctly in our test environment
https://mobility.api.opendatahub.testingmachine.eu/v2/flat/NOI-Place/*/latest?limit=-1&select=tmetadata,mvalue&shownull=true&distinct=true
