### ISSUE TITLE
As an air quality expert I would like to see the elaborations associated to the measurements some air quality innovative sensors improved with new calibration curves (without ozone)

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#187]

**Comment by rcavaliere** [comment]
For sensors AQ6, AQ7, AQ9, AQ10 the ozone sensor is not working anymore. UNITN has found new calibration curves for the computation of the processed elaborations of NO and NO2. The DC has to be fixed so that for the indicated sensors NO and NO2 has to be processed according to this different computations.
[200724_calibrazioneAQ_noO3.xlsx](https://github.com/noi-techpark/bdp-commons/files/5102922/200724_calibrazioneAQ_noO3.xlsx)

**Comment by rcavaliere** [comment]
@bertolla I assume that the most efficient way is to change the mapping table defined here: https://github.com/noi-techpark/bdp-commons/blob/master/data-collectors/environment-a22/src/main/resources/mappings/processorParameters.csv without changing anything in the code. The new calibration curves in fact substitute the previous ones. If you agree on this, I can do this task.

**Comment by rcavaliere** [comment]
@bertolla, please integrate this PR in order to implement this user story: https://github.com/noi-techpark/bdp-commons/commit/2b59e317097599a7e08b6169d2d407060652d0a9

**Comment by rcavaliere** [comment]
@bertolla did you complete the complete integration of this in our production environment?

**Comment by bertolla** [comment]
No, as we discussed I first had to fix all the tests and see if it works, thats why we put it back to todo. I will do it now

**Comment by bertolla** [comment]
@rcavaliere I deployed your changes the same day. Have you checked the values generated now?

**Comment by rcavaliere** [comment]
I already tested this and seems to work now. I will ask the colleagues of the University of Trento to test further this
