### ISSUE TITLE
As an air quality expert I would like that the elaborations carried out on the A22 innovative air quality data are done also on a hourly basis, so that they are more robust and usable by 3rd party applications

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#188]
Implementation logic should be follow:
- [x] for every pollutant to be elaborated (e.g. NO-Alphasense, NO2-Alphasense, O3, PM10), compute on a hourly basis (e.g. at 9:00, 10:00, etc.) the average of all measurements collected during the previous hours (e.g. 8:00 - 8:59, 9:00 - 9:59, etc.)
- [x] once the hourly "raw" measurements are computed, compute also the associated elaboration, by using the same calibration curve.
Please note that the no additional data types should be created, a different period has to be associated to the existing data types.

**Comment by rcavaliere** [comment]
This elaboration will be implemented externally (getting data from API and providing results to the writer -> the writer v2 will be used, and therefore this can be completed once the writer v2 is available for use)

**Comment by rcavaliere** [comment]
@bertolla did you start with this implementation? I don't know why this fall at the end of the priority list... this would be one of the most important developments to be done in this sprint!

**Comment by bertolla** [comment]
No, I haven't since we are still working on the dockerization of bdp. It won't be done in this sprint on production. Probably on testing.

**Comment by sseppi** [comment]
Since @bertolla won't be able to finish this issue before to leave thisi issue will be blocked.

**Comment by rcavaliere** [comment]
@bertolla can we give more priority to this user story? Can you at least start with this development next week?

**Comment by bertolla** [comment]
Data needs authentication and on this test env it's only available till 6/10
See here an example:
https://analytics.opendatahub.testingmachine.eu/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:1601503200000,%22to%22:1601676000000%7D,%22graphs%22:%5B%7B%22category%22:%22Air%20Quality%22,%22station%22:%22AUGEG4_AIRQ01%22,%22station_name%22:%22103.700_APPA%20BZ%22,%22data_type%22:%22CO2_raw%22,%22unit%22:%22%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:0%7D,%7B%22category%22:%22Air%20Quality%22,%22station%22:%22AUGEG4_AIRQ01%22,%22station_name%22:%22103.700_APPA%20BZ%22,%22data_type%22:%22CO2_raw%22,%22unit%22:%22%22,%22period%22:%223600%22,%22yaxis%22:1,%22color%22:1%7D%5D%7D

**Comment by rcavaliere** [comment]
I have mode some test verifications and everything seems reasonable to me. Let's go in production

**Comment by bertolla** [comment]
Haven't applied the modifications yet which we talked in the last meeting so please wait for now
