### ISSUE TITLE
As an ODH user I would like to get the bike rental data of Papin Sport

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#226]
DC is developed by Patrick Pucher on behalf of Papin. 

The user story cover:
- [x] the integration of the DC in testing environment
- [ ] the verification of the correct functioning, documentation, proper data storage in the DB
- [ ] the release in the production environment

**Comment by bertolla** [comment]
@rcavaliere The documentation says:`the service endpoints (credentials must be provided setting the parameter 'app_auth_token');`
Is there a token I need?

**Comment by rcavaliere** [comment]
Yes, I forward this via mail

**Comment by bertolla** [comment]
datacollector is now running but it only executes once a day at 1

**Comment by rcavaliere** [comment]
@bertolla thanks! Can't we change the scheduler, so that the data are at least updated once every hour?

**Comment by rcavaliere** [comment]
@bertolla please integrate the PR https://github.com/noi-techpark/bdp-commons/pull/233 this should solve the last issues

**Comment by bertolla** [comment]
Seems to be working now. A thing I would like to change, and this is a thing I can do, is to rename stationcodes in "origin+stationcode" since they are not really unique.

**Comment by rcavaliere** [comment]
Ok, change the stationcode. 
Can you set the DC so that we ingest data every 10 minutes?

**Comment by bertolla** [comment]
You can test using ninja: https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BikesharingStation/*/latest?limit=-1&where=sorigin.eq.BIKE_SHARING_PAPIN,sactive.eq.true
or just analytics: https://analytics.opendatahub.testingmachine.eu/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:1613257200000,%22to%22:1614034800000%7D,%22graphs%22:%5B%7B%22category%22:%22Bike%20sharing%22,%22station%22:%22BIKE_SHARING_PAPIN:88%22,%22station_name%22:%22Papin%20Sport%20Hotel%20Mandelhof%22,%22data_type%22:%22availability%22,%22unit%22:%22%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:0%7D,%7B%22category%22:%22Bike%20sharing%22,%22station%22:%22BIKE_SHARING_PAPIN:90%22,%22station_name%22:%22Papin%20Sport%20Camping%20Gretl%20am%20See%22,%22data_type%22:%22isClosed%22,%22unit%22:%22%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:1%7D%5D%7D

**Comment by rcavaliere** [comment]
Ok, tested, works fine in my opinion. Let's go in production!

**Comment by bertolla** [comment]
I adapted the production pipeline and deployed it. I also deployed the new opendatarules for bikesharing. Cheers, Patrick

**Comment by rcavaliere** [comment]
Thanks!
