### ISSUE TITLE
As a meteo expert I would like to see the correct measurement unit associated to type "wind speed" related to the meteorological stations provided by the Province of Bolzano as open data

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#235]
Issue described here: https://issues.opendatahub.bz.it/Ticket/Display.html?id=1781

**Comment by bertolla** [comment]
Which windspeed? Currently we have this:
```
      cname      | cunit |    description     
-----------------+-------+--------------------
 wind-gust-speed | m/s   | Velocitá raffica
 wind10m_speed   | m/s   | 
 wind-speed      | Km/h  | Velocità del vento
```
I guess `wind10m_speed` is causing the problem and this is data coming from **meteotrentino**

**Comment by rcavaliere** [comment]
It's "wind-speed", should be m/s

**Comment by bertolla** [comment]
Are you sure? I mean, it's right for data coming from SIAG but maybe not for the one coming from FAMAS-traffic.

**Comment by rcavaliere** [comment]
Ok please check if the data collectors are using the same data type. If yes, we should create or two different data types (one for measurement unit) or convert the data in the correct measurement unit before integrating it in the ODH

**Comment by bertolla** [comment]
The use same unit but something is not working correctly when syncing datatypes. I'm investigating right now

**Comment by rcavaliere** [comment]
Sure that is OK? 
See this example...
![Screenshot from 2021-03-02 21-54-07](https://user-images.githubusercontent.com/9825179/109713770-e8c35a80-7ba1-11eb-89dd-52acef4c52b7.png)

**Comment by bertolla** [comment]
```
 id |   cname    |       created_on        | cunit |    description     | rtype | meta_data_id 
----+------------+-------------------------+-------+--------------------+-------+--------------
  2 | wind-speed | 2013-12-11 14:21:57.635 | m/s   | Velocità del vento |       |           33
```

**Comment by bertolla** [comment]
I noticed a thing now:
```
 id |   cname    |       created_on        | cunit |    description     | rtype | meta_data_id 
----+------------+-------------------------+-------+--------------------+-------+--------------
  2 | wind-speed | 2013-12-11 14:21:57.635 | m/s   | Velocità del vento |       |           33
(1 row)

 id |   cname    |       created_on        | cunit |    description     | rtype | meta_data_id 
----+------------+-------------------------+-------+--------------------+-------+--------------
  2 | wind-speed | 2013-12-11 14:21:57.635 | Km/h  | Velocità del vento |       |           33

```

**Comment by bertolla** [comment]
I think I got a hunch. Datatype syncing is happening every hour also in traffic-bz which means that the second which calls overwrites the first. Going deeper I noticed that the values being saved are quiet similar:
```
 2.4 | 06040WS           | SIAG          | 2021-03-03 08:20:00
 5 | 35100WS           | SIAG          | 2021-03-03 08:20:00
 1.4 | 50400WS           | SIAG          | 2021-03-03 08:20:00
 0.7 | 50500MS           | SIAG          | 2021-03-03 08:10:00
 2.5 | municipalitybz:10 | FAMAS-traffic | 2021-02-10 13:20:00
```
Which means either the province is providing wrong units or FAMAS is.

**Comment by rcavaliere** [comment]
It's much more probable that FAMAS is wrong here...

**Comment by bertolla** [comment]
For now it should be working like we discuessed
