### ISSUE TITLE
As a meteo expert I would like to receive back precipitation data related to the weather stations of the Province of Bolzano

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#239]
See precipitation data types
![Screenshot from 2021-03-09 13-34-29](https://user-images.githubusercontent.com/9825179/110471322-4bee4900-80dc-11eb-8c66-2d7c14ed2ba2.png)

**Comment by bertolla** [comment]
This is the endpoint we call:
http://dati.retecivica.bz.it/services/meteo/v1/timeseries

**Comment by bertolla** [comment]
The commit did not fix the problem, but after a lot of grinding I found out that the period is wrong. In the datacollector the period is hardcoded to 600 for every datatype. Precipitation should be 300. Is the webservice providing this information so we could implement it dynamically?
