### ISSUE TITLE
As a traffic analyst I would like to have also air quality measurements taken by the A22 innovative sensors averaged on 60 minutes

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#244]
Elaboration was already implemented, but in relation to bug fix related to the issue #236 it is likely that this elaboration was corrupted or disabled.

**Comment by bertolla** [comment]
Who is calculating this averages? Is it a different dc? Can you point to the dc which is handling this task?

**Comment by rcavaliere** [comment]
I think it is the same DC, can you please check?

**Comment by bertolla** [comment]
It's not the same. It's a java application created to execute this task. See https://github.com/noi-techpark/bdp-elaborations/tree/master/airquality-elaborations

**Comment by bertolla** [comment]
I updated all dependencies and redeployed the application. Seems to work now. Can you confirm?

**Comment by rcavaliere** [comment]
Yes, seems to work! Let's leave this user story in testing for a while so to see the behavior for a couple of days

**Comment by rcavaliere** [comment]
@bertolla can we improve the logic so to have the latest 60-minutes averages fast real-time? E.g. make the computation soon after the 00:00

**Comment by bertolla** [comment]
This is not yet working as expected. Data is not always up to date and some types/stations are not being calculated.
This is due to long intervals of no data and insufficient data (we have set a minimum of 30 datapoints to do average calculations).
