### ISSUE TITLE
As an air quality expert I would like to avoid to analyze dirty data that is related to intercalibration periods

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#283]
![190201_Intercalibrazione_ML5-2](https://user-images.githubusercontent.com/9825179/121589407-4f74d180-ca37-11eb-8bb7-1f2c39df56f9.jpg)
The low-cost innovative air quality sensors of A22 need every 6 months (on average) to be calibrated again in order to improve the coefficients used in the elaboration post-processing. The calibration is typically done in an inter-calibration site, where sensors' measurements are taken in parallel with a reference air quality station. During this periods, the data collected should be deleted since it does not refer to the measurement point in which they are installed.

Periods to be cancelled:
AQ1:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 2/17/2021- 3/4/2021 , 3/19/2021 - onwards
AQ2:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ3:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ4:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 1/13/2021 - 2/5/2021
AQ5:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ6:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ7:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ8:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019,  4/20/2021 - 5/19/2021
AQ9:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019,  3/26/2021 - 4/16/2021
AQ10:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021  
AQ11:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ12:6/10/2018 - 6/30/2018, 2/1/2019 - 2/14/2019, 3/26/2021 - 4/16/2021
AQ13: 11-26-2019 - 12-17-2019, 1/13/2021 - 2/5/2021

**Comment by bertolla** [comment]
@rcavaliere 
How are this timestamps to be interpreted?
For Example:
Does `AQ1:6/10/2018 - 6/30/2018`
mean `AQ1:6/10/2018 00:00:00 - 6/30/2018 23:59:59` ?

**Comment by rcavaliere** [comment]
yes, correct!

**Comment by bertolla** [comment]
All measurements independent from the type?

**Comment by rcavaliere** [comment]
yes, all types associated to that sensor

**Comment by bertolla** [comment]
Ok I have done it for all sensors.
For the future we want to use the spreadsheet. Is it one we find on google spreadsheet?
I guess no.

**Comment by bertolla** [comment]
Things to do:
- [ ] create a strategy to avoid missing out maintenance periods for sensors
- [ ] define api for ninja to get station history

**Comment by rcavaliere** [comment]
My proposal would be the following:
- [ ] create a Google Sheet file in which intercalibration periods have to be inserted
- [ ] in case of a new intercalibration period, data should be associated to "calibration" types (not cancelled) 
But this should be a new user story...

**Comment by bertolla** [comment]
which means currently there is no google spreadsheet and there is implementation to be done

**Comment by rcavaliere** [comment]
@bertolla I suggest to close this user story and to open a new one. Is this OK for you?

**Comment by bertolla** [comment]
Yes, we can do that, but my suggestion on using the google spreadsheet to define periods was based on the assumption that there is already one we are using. Creating additional complexity and implement this to the datacollector is surely not the best way, if so.
They should be the one to send a flag or not send data if they are doing recalibration/maintenance jobs on the sensors.

**Comment by rcavaliere** [comment]
This is not so easy to implement in their back-end. But OK, let's close this issue and open a new one when a new calibration will be planned (it will be 2022...)
