### ISSUE TITLE
Implementation of a measurement / measurementhistory table able to save a JSON as value

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#290]
High Priority, Deadline 17 September (an working alpha version)

Associated to epic #289 

As documented in the attached specification, some dataset need a new table measurement / measurementhistory table able to save a JSON as value 
[210802_SpecificheIntegrationeODH.pdf](https://github.com/noi-techpark/bdp-commons/files/6917360/210802_SpecificheIntegrationeODH.pdf)

Tasks foreseen:

@bertolla

- [x] Create DB model
- [x] ~~Writer API enhancement~~ //this is not needed since it's abstracted in the backend

@Piiit (or @bertolla with support by @Piiit)
- [x] Ninja API enhancement
- [x] Open `s.origin=ON_DEMAND_MERANO` data to be open data now
- [x] Blocked by https://github.com/noi-techpark/it.bz.opendatahub.api.mobility-ninja/issues/16

**Comment by bertolla** [comment]
I implemented the needed changes but I would like to deploy it only once the new Event API is tested and deployed to production.

**Comment by bertolla** [comment]
Test database can handle json values. This is supported in bdp version 5.4.0-SNAPSHOT and will be released once tested.

**Comment by rcavaliere** [comment]
OK, that's means that we can test this the on-demand DC?

**Comment by bertolla** [comment]
Sure, even though I would suggest to first test it internally to avoid a back and forth between us and the external provider. Also, Peter M. needs to finish the adaptations in ninja and an external provider cannot see the changes/data if that's not implemented

**Comment by rcavaliere** [comment]
@Piiit this user story has quite a high priority. Can you complete this by the end of this sprint?

**Comment by Piiit** [comment]
@rcavaliere I implemented it, and tested to some extend... Improved also the select and where clause to better understand json subqueries... it is still beta thou, we need more tests and some code refactoring

**Comment by Piiit** [comment]
Re-read the main comment, the writer can stay the same... but we need to deploy the DC that writes into the JSON tables

**Comment by Piiit** [comment]
So we can practically close this and focus on #289 to test it in a real-life scenario, right @rcavaliere ?
