### ISSUE TITLE
As a project manager I would like to integrate the DC related to the bike chargers supplied by Ecospazio in our infrastructure

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#296]
**UPDATE BY @Piiit **

- [x] @Piiit Merge: The Data Collector has been developed by Catch & Solve. PR: https://github.com/noi-techpark/bdp-commons/pull/302
- [x] @rcavaliere Provide: We need to ingest in Jenkins the authentication credentials requested by Ecospazio --> set it here https://passwords.testingmachine.eu/app/passwords/view/766e6e54-6c14-4a0a-851d-b719e87762d0
- [x] @noctho or @davidebz updates the README about the connector setup
- [x] @piiit creates the testing pipeline

**Comment by Piiit** [comment]
@rcavaliere I need the credentials... blocked meanwhile

**Comment by Piiit** [comment]
@noctho I need some information to deploy this DC...

```
connector.url=https://maas.ecospazio.it/api
connector.apiKey.name=
connector.apiKey.value=
```

value is the token here, that I have got from @rcavaliere ... but what is the name?

**Comment by noctho** [comment]
name is 'Token' and value is the token. Its simple the name of the HTTP header.

```
connector.url=https://maas.ecospazio.it/api
connector.apiKey.name=Token
connector.apiKey.value=
```

**Comment by Piiit** [comment]
@noctho Works, thank you... why didn't you hardcode it?

**Comment by noctho** [comment]
I don't remember exactly why, but I think it was because at the beginning when I implemented it we only had the token and didn't know that the header name was 'Token'. Then when we knew that, I kept it parameterized because it is not a standardized header name like Authorization.

**Comment by Piiit** [comment]
OK, I keep it then configurable

**Comment by Piiit** [comment]
@rcavaliere The DC is online... see https://mobility.api.opendatahub.testingmachine.eu/v2/flat/BIKE_CHARGER/* for instance

Please test

**Comment by rcavaliere** [comment]
@noctho for the two different station types we don't see all measurement types expected, i.e.:

- [ ] state for stationtype = BIKE_CHARGER
- [ ] state and usageType for stationtype = BIKE_CHARGER_BAY

**Comment by rcavaliere** [comment]
@Piiit it was my fault, the data were correctly stored in measurementstring. Evertything OK there, we can go in production with this Data Collector

**Comment by Piiit** [comment]
@rcavaliere Done, please test the output on production... should we also add it to the analytics web page?

**Comment by rcavaliere** [comment]
@Piiit thanks! But it's correct that I don't see real-time data? For analytics don't worry, I can configure it so to see this dataset as well.
