### ISSUE TITLE
As a project manager I would like to check the status of the DC On-Street-Parking-BZ

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#433]
Like #432 
Reference DC: https://github.com/noi-techpark/bdp-commons/tree/main/data-collectors/onstreet-parking-bz

**Comment by rcavaliere** [comment]
@Piiit @dulvui I have seen that the DC ha stopped again to send data, do we have this time an issue with the Data Provider or is always a problem at our side?

**Comment by dulvui** [comment]
I'll check now
