### ISSUE TITLE
As a project manager I would like to check the status of the Bluetooth Data Collector

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#435]
- [x] Like #432, reference Data Collector: https://github.com/noi-techpark/bdp-commons/tree/main/data-collectors/vehicletraffic-bluetooth
- [x] Please also check that the elaboration chain based on the Bluetooth data is functioning again as expected (there is an application writing directly into the database, without passing through the writer if I remember well; results are saved in relation to LinkStations). --> https://github.com/noi-techpark/BluetoothTrafficElaboration
    > Now a separate issue: https://github.com/noi-techpark/bdp-core/issues/256
- [x] Check that all BluetoothStations are correctly visible (active = TRUE)

**Comment by rcavaliere** [comment]
@Piiit please have a look why we have several sensors set as not available, in particular those installed in Merano

**Comment by Piiit** [comment]
@rcavaliere I give this issue to @dulvui now, since he is already working on noi-techpark/bdp-core#256

**Comment by dulvui** [comment]
@rcavaliere Are there still problems with the sensors of Merano or did the LinkStation fix solve it?

**Comment by rcavaliere** [comment]
@dulvui we can close this!

**Comment by dulvui** [comment]
perfect
