### ISSUE TITLE
As a project manager I would like to check the status of the DC "Bike Sharing Papin"

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#442]
Like #432 
Reference DC: https://github.com/noi-techpark/bdp-commons/tree/main/data-collectors/bikesharing-papin

Papin Endpoint gives 408 timeout

**Comment by Piiit** [comment]
@rcavaliere The issue has been solved already, do you need some dashboard or alerting to check the status continuously, or did you simply mean to check it once?

**Comment by rcavaliere** [comment]
@Piiit at present the Grafana dashboard is sufficient! Let's close this issue
