### ISSUE TITLE
A22 Parking DC should not have (if not necessary) the types "free" and "occupied"

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#490]
I don't know why, but A22 parking areas have now as types "free" and "occupied". At present, A22 provides the information "occupied" only for a parking area (Sadobre), for the others we just receive a state. Please have a look at the attached specifications.
[210813_SpecificheIntegrazione_A22_Parcheggi_v2.pdf](https://github.com/noi-techpark/bdp-commons/files/8521833/210813_SpecificheIntegrazione_A22_Parcheggi_v2.pdf)

**Comment by dulvui** [comment]
I checked the datacollector and it calculates the occupied value with "capacity - free", so it doesn't use a value from A22 but calculates it on its own. Should I remove this state or should i leave it as it is?

**Comment by rcavaliere** [comment]
@dulvui the point is that the type "free" should not be associated to these parking areas. So, if you correct this, the automatic elaboration for the "occupied" type should be automatically fixed.

**Comment by rcavaliere** [comment]
@dulvui I think we should proceed here as follows:
- [ ] control which parking areas coming from the A22 Parking Data Collector have the "free" (or "occupied") type
- [ ] for all parking areas which do **not** have the "free" (or "occupied") type, delete the time series in production and testing environments referred to these types
- [ ] ensure that the automatic elaboration which computes the free parking areas (or occupied) based on the capacity does only consider parking areas that have this type associated

**Comment by dulvui** [comment]
@rcavaliere I can confirm that Sadobre is the only station with 'free' data-type associated. All other stations will no longer have an entry in measurements table, only the capacity in the stations metadata will be available.
Should I delete also the timeseries data in measurements history?

**Comment by rcavaliere** [comment]
@dulvui I see the improvement already in the production environment, is this possible? However, this is the expected behaviour, so in my view the issue is solved. If this is already applied in production, the result of your query to /latest is correct.

**Comment by dulvui** [comment]
@rcavaliere Yes I deployed yesterday afternoon to production.
Okay awesome!
