### ISSUE TITLE
Remove parking.bz.it footer

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#532]
See screenshot (all this part should be removed, since no more actual)

![Screenshot from 2022-05-27 10-41-59](https://user-images.githubusercontent.com/9825179/170664652-9398c5b1-c5be-4701-ac10-9a455b6c24e2.png)

**Comment by dulvui** [comment]
Footer removed.

**Comment by dulvui** [comment]
@rcavaliere also the logos are now removed

**Comment by rcavaliere** [comment]
Perfect!

**Comment by ohnewein** [comment]
Great work!

I just noticed that on the map view there is no attribution to Open Street Map, which is providing the map data. I think we have to add this attribution string in the bottom of the map view.

![Screenshot_20220623-070339](https://user-images.githubusercontent.com/414797/175218570-f6502096-0372-463c-97dc-fcce6c140cc4.jpg)

**Comment by dulvui** [comment]
@ohnewein The attribution was visible on desktop but not on mobile.
Now the attribution position is fixed and it is also visible on mobile.

**Comment by ohnewein** [comment]
Thank you @dulvui ! Great job!
