### ISSUE TITLE
Fix parking forecast bug

### ISSUE THREAD

**Issue by davidebz** [noi-techpark/bdp-commons#540]
To fix please change the MainParkingForecast.java class at line 89

from 

new SimpleRecordDto(timestampMillis, propertyValue, datatypeConfiguration.getPeriod()));

to

new SimpleRecordDto(forecastDatatypeTimestamp.toInstant().toEpochMilli(), propertyValue, datatypeConfiguration.getPeriod()));

**Comment by rcavaliere** [comment]
@Piiit @dulvui please also ensure to cancel all the predictions that were imported with the deployment of this component, so that we have clean predictions in production once we deploy this

**Comment by davidebz** [comment]
I have send the pull request on the main branch, I hope is ok. Sincerely I have not testet the fix. Please inform us when is in production so we can immediately check that is correct

**Comment by dulvui** [comment]
I stopped the running data-collectors in testing and production. I will delete the data first in the testing db, check that everything is fine and then delete the data in production.
Deleting data takes a lot of time (the delete queries need some hours) so we will probably be ready on Monday to merge this PR and redo the deployment with the bugfixe.
@davidebz I'll let you know when the bugfix is running on testing, so you can check if everything works fine

**Comment by dulvui** [comment]
@rcavaliere Okay that works fine

**Comment by rcavaliere** [comment]
@davidebz I think that the forecasts still have issues in the timestamp considered, have a look at this example:

https://analytics.opendatahub.testingmachine.eu/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:%222022-06-16%22,%22to%22:%222022-06-23%22%7D,%22graphs%22:%5B%7B%22category%22:%22Parking%22,%22station%22:%22108%22,%22station_name%22:%22P08%20-%20BZ%20Centro%20via%20Mayr%20Nusser%22,%22data_type%22:%22free%22,%22unit%22:%22%22,%22period%22:%22300%22,%22yaxis%22:1,%22color%22:3%7D,%7B%22category%22:%22Parking%22,%22station%22:%22108%22,%22station_name%22:%22P08%20-%20BZ%20Centro%20via%20Mayr%20Nusser%22,%22data_type%22:%22parking-forecast-30%22,%22unit%22:%22%22,%22period%22:%221800%22,%22yaxis%22:1,%22color%22:2%7D,%7B%22category%22:%22Parking%22,%22station%22:%22108%22,%22station_name%22:%22P08%20-%20BZ%20Centro%20via%20Mayr%20Nusser%22,%22data_type%22:%22parking-forecast-60%22,%22unit%22:%22%22,%22period%22:%223600%22,%22yaxis%22:1,%22color%22:3%7D%5D%7D

**Comment by uh8st3nnsj** [comment]
You need to compare the forecasts to "occupied" instead of "free", then it looks OK:

<img width="1234" alt="Screenshot 2022-06-23 at 23 31 12" src="https://user-images.githubusercontent.com/108098924/175407342-f33d23ad-9ff5-4ea8-9ad3-bf5160ac5825.png">

Actually there are no current forecasts, but that might be because it was a test.

-- Chris

**Comment by rcavaliere** [comment]
Ah sorry you are right, I compared the wrong type. Looks fine, @dulvui we can put this in production

**Comment by dulvui** [comment]
@davidebz @rcavaliere The dc is now running in production and it looks fine. Please check if everything is correct.
