### ISSUE TITLE
As a project manager I would like that the new car pooling Data Collector connected to the ummadum car pooling service is integrated in the Open Data Hub

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#553]
PR to be integrated (DC developed by CatchSolve): https://github.com/noi-techpark/bdp-commons/pull/552

**Comment by dulvui** [comment]
PR is integrated and running on testing

**Comment by rcavaliere** [comment]
@ohnewein @dulvui @sseppi Contract still under discussion, but we are near to close it.

**Comment by rcavaliere** [comment]
@dulvui @clezag in short we can start to put in production this Data Collector. I have however seen that some fields of the CSV are not currently provided via API (e.g. start time of the trips). Can you please add this?

**Comment by dulvui** [comment]
@rcavaliere The carpooling data is now it is open and available on testing. The missing fields are saved as measurement json data.
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/CarpoolingTrip/
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/CarpoolingTrip/*/latest

**Comment by dulvui** [comment]
@rcavaliere Should I also deploy to production?

**Comment by rcavaliere** [comment]
@dulvui sorry, not yet. We still need the final agreement with ummadum.
