### ISSUE TITLE
parking-forecast: data from endpoint is not updating since 7/9/2022

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/bdp-commons#563]
The latest update of the parking-forecast data was made on the 7/9/2022, so the is a problem with the endpoint not updating the data.
@rcavaliere Can you contact STA or who is in charge of this endpoint and inform them of the problem?

Here you can see the data with the publish_timestamp set to 2022-09-07 14:11:49.745657+00:00:
https://web01.sta.bz.it/parking-forecast/result.json

**Comment by rcavaliere** [comment]
@dulvui thanks for the information, I already noticed it. I will ask STA and Chris M. to check this.
