### ISSUE TITLE
As a Data Consumer I would like to access to the planned data of the SkyAlps air transport services

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#569]
- [x] Data Collector development by GruppoFOS
- [x] Data Colector PR integration, testing, deployment in production

**Comment by rcavaliere** [comment]
@dulvui you can start the integration of this PR: https://github.com/noi-techpark/bdp-commons/pull/570
As usual, please also check that everything is complete and well documented and organized, according to our internal guidelines.

**Comment by rcavaliere** [comment]
@sseppi with @mrabans and @dulvui we found a better way to model the data in the Open Data Hub also taking in consideration that in short we might have real-time data as well. Draft specification are attached. To be internally finalized, then @dulvui can improve the Data Collector, we can test it and then put in production

[2211122_SpecificheIntegrazioneODH_NOI_v1.3.docx](https://github.com/noi-techpark/bdp-commons/files/10087191/2211122_SpecificheIntegrazioneODH_NOI_v1.3.docx)

**Comment by mrabans** [comment]
@rcavaliere to respond your questions about basic airport information and GPS positions, this might be a starting point: https://ourairports.com/data/

See for example line 39868 in this file to find information about Bolzano airport: https://davidmegginson.github.io/ourairports-data/airports.csv

**Comment by rcavaliere** [comment]
@dulvui please remember to complete the sorting feature of the provided flights in case a request with a time interval is made, then we can make a final testing and put the Data Collector in production

**Comment by mrabans** [comment]
> @rcavaliere to respond your questions about basic airport information and GPS positions, this might be a starting point: https://ourairports.com/data/
> 
> See for example line 39868 in this file to find information about Bolzano airport: https://davidmegginson.github.io/ourairports-data/airports.csv

@rcavaliere Should we rethink about an integration of the airports?

**Comment by dulvui** [comment]
@rcavaliere @mrabans  I checked now again for the station sorting and it is quite complicated to implement this for me. And because I still don't know the code of the API well, it might have (for sure ;-) ) unwanted side effects.
I think the best solution is limiting the flights to the time frame using the unix timestamps and do the sorting on client side.

**Comment by rcavaliere** [comment]
> > @rcavaliere to respond your questions about basic airport information and GPS positions, this might be a starting point: https://ourairports.com/data/
> > See for example line 39868 in this file to find information about Bolzano airport: https://davidmegginson.github.io/ourairports-data/airports.csv
> 
> @rcavaliere Should we rethink about an integration of the airports?

@mrabans yes, it is on my to do list. We need this for implementing the GTFS export, I need to find the time to draft a document for GruppoFOS so to proceed with this implementation

**Comment by rcavaliere** [comment]
> @rcavaliere @mrabans I checked now again for the station sorting and it is quite complicated to implement this for me. And because I still don't know the code of the API well, it might have (for sure ;-) ) unwanted side effects. I think the best solution is limiting the flights to the time frame using the unix timestamps and do the sorting on client side.

@dulvui I agree with you. However, this might a good feature that in general the Open Data Hub should support, so maybe let's open a new user story for this
