### ISSUE TITLE
As an air quality export, I would like to have from the Open Data Hub not only the traffic data but elaborated information about the related emission produced

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#581]
Integration of the PR by u-hopper with the AI-as-a-Service tool that implement the emission calculation implemented by CISMA

Logic of functioning:

- Reading of data from Open Data Hub API
- Calculation of emissions (AI model)
- Provision of elaborated information to the Open Data Hub, similar as a Data Collector

This user story deals with the integration and testing of this development

**Comment by rcavaliere** [comment]
@dulvui after the meeting had with CISMA and u-hopper, you can put this in production, as agreed in the meeting

**Comment by rcavaliere** [comment]
@dulvui wonderful, let's see if everything is computed without issues!

**Comment by dulvui** [comment]
@rcavaliere The first run is now completed and the scheduler runs every 10 minutes to calculate the latest data.
