### ISSUE TITLE
As STA Green Mobility I would like that also charging stations that are not connected to a back-end system in real-time are statically inserted in the Open Data Hub and made available through it, so to have a better overview of all available charging offer in South Tyrol

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#582]
- [x] Data Collector development (linked to shared Google Excel file)

**Comment by rcavaliere** [comment]
@dulvui we can start with this small development

**Comment by dulvui** [comment]
@rcavaliere Okay I will start this week.
Just to be sure, I just need to use our Google Sheets datacollector with the configuration for this sheet and create new Stations?

**Comment by rcavaliere** [comment]
Yes, we need the ability to give 3rd parties access to a Google sheet and let them insert their (static) charging stations

**Comment by dulvui** [comment]
@clezag will to do this task, so he also gets a little introduction to the data-collector side

**Comment by rcavaliere** [comment]
@clezag @dulvui I have prepared a short technical note with all relevant details on how the data should be inserted in the shared file and integrated in the Open Data Hub tables. There is some fine tuning needed with respect to this indications, i.e.:

- [ ] I would rename the column in the shared file "POINT_NAME" (plug is more associated to the outlet, which could be misleading
- [ ] I would foresee a slight different way to generate the stationcodes. I would suggest to have an additional name for the data provider (already inserted), which should be used for the prefix
- [ ] Please check if the plugs are correctly stored. Probably we need some example with real data to check this (I can provide some data!)
- [ ] Not all relevant metadata is currently stored. Make sure that all fields are present in the JSON here

[230125_SpecificheIntegrazione_DatiStatici_NOI_v2.1.pdf](https://github.com/noi-techpark/bdp-commons/files/10496517/230125_SpecificheIntegrazione_DatiStatici_NOI_v2.1.pdf)

**Comment by clezag** [comment]
@rcavaliere Thanks for the feedback!
I've implemented the changes outlined in the document.
As discussed in person, there are some minor changes to how origin and stationcode are populated.

DB-side now looks fine to me at a cursory glance, 
but if you have some real data, that would certainly be useful to do a more thorough check.

**Comment by rcavaliere** [comment]
@clezag wonderful. Today I got a first list of real charging stations that we can use for testing. I will insert the data in the shared file, hopefully tomorrow

**Comment by rcavaliere** [comment]
@clezag I have inserted some real data of a real operator in the shared file. Let's see if we import it in the expected way!

**Comment by rcavaliere** [comment]
@clezag I tested this, seems OK for me. Nice work! I would however suggest to leave in the testing environment here until we have the first agreements signed with Data Providers wanting to share data in this modality, like for example VEK as in the real data example we have already implemented..

**Comment by rcavaliere** [comment]
@clezag we can put this Data Collector in production! The data in the file: https://docs.google.com/spreadsheets/d/1ucCQzAVGmvyRpeq-lIPffALQaWcG4LfPakc2mjt79fY/edit#gid=0 are already the one to be published

**Comment by clezag** [comment]
@rcavaliere the data collector is now in production

**Comment by rcavaliere** [comment]
@clezag very good! I think that our e-mobility web-components still do not show this data, but I open a new user story to check this for the next sprint

**Comment by rcavaliere** [comment]
@clezag the reference file for the production environment is always https://docs.google.com/spreadsheets/d/1ucCQzAVGmvyRpeq-lIPffALQaWcG4LfPakc2mjt79fY/edit#gid=0, or? We have another Data Provider!

**Comment by clezag** [comment]
@rcavaliere great news!
Yes, the spreadsheet is still the same
