### ISSUE TITLE
As a SkyAlps Data Consumer I would like to get also the fare and real-time data of the flights

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#601]
It should be enhancement of the current version of the SkyAlps Data Collector, which currently integrates "just" the planned flight data. Such enhancement should be carried by considering the attached specifications
[221216_SpecificheIntegrazioneODH_NOI_v2.1.pdf](https://github.com/noi-techpark/bdp-commons/files/10463981/221216_SpecificheIntegrazioneODH_NOI_v2.1.pdf)

**Comment by rcavaliere** [comment]
@mrabans @dulvui I have tested this new version of the Data Collector, I am really happy on how we have integrated this dataset, nice work! Let's go on production!

**Comment by dulvui** [comment]
@mrabans @rcavaliere Awesome! Now it is in production and you can already see the realtime and pricing data there.

**Comment by mrabans** [comment]
@rcavaliere @dulvui So cool!!
