### ISSUE TITLE
As PAB traffic events Data Consumer I would like that events have also a reference to subcategories, in order to better filter them

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#658]
If we better look at the end-point from which we read the data (http://www.provinz.bz.it/vmz/traffic.json), we see that events have a two-level classification (primary and secondary category). At present we consider only the first classification for distinguishing events. I would suggest to also include the second category, so that e.g. we can decide to just visualize certain subcategories on the map of analytics.

I would use the same approach as for A22 event, so that we have one category field and all possible categories automatically computed. 

User story to do's:
- [x] Specification enhancement by @rcavaliere 
- [x] Data Collector modification implementation

**Comment by rcavaliere** [comment]
@dulvui please find here the review of the specification. Actually I have seen that the event category is mapped with the field "TyCode" of the web-service, not "subTycode" as originally planned. I suggest to consider both values for our category field, as done for the A22 Events Data Collector. In that way we can have on the map a better selection of events to be visualized

[230915_SpecificheIntegrazione_v2.pdf](https://github.com/noi-techpark/bdp-commons/files/12616199/230915_SpecificheIntegrazione_v2.pdf)

**Comment by dulvui** [comment]
@rcavaliere The subcategory type is now also added to the category field like this `tycodeIt subTycodeIt | tycodeDe subTycodeDe`

**Comment by rcavaliere** [comment]
@dulvui perfect, now it is possible to filter the events by category in a more granular way!
