### ISSUE TITLE
As STA I would like to integrate the real-time parking data of my parking stations in Bressanone and Brunico from the newly available Skidata API, so that I can show this data on the suedtirolmobil channels

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#663]
- [x] Finalization of the technical specifications (first draft already available - see first document below)
- [x] Testing the end-point of Skidata
- [x] Development of the Data Collector
- [ ] Finalization of contract between STA and SkiData

[231219_SpecificheIntegrazione_NOI_v1.1.docx](https://github.com/noi-techpark/bdp-commons/files/13712382/231219_SpecificheIntegrazione_NOI_v1.1.docx)

[230728_SpecificaSkidata.pdf](https://github.com/noi-techpark/bdp-commons/files/13712380/230728_SpecificaSkidata.pdf)

**Comment by dulvui** [comment]
@rcavaliere The datacollector has now all data on testing. The only thing I changed from your proposal is the datatype naming: I used English translations for SostaBreve = ShortStay and Abbonati = Subscribers. Should I use the italian names?
As GPS point I simply used the coordinates of Bolzano as placeholder.

**ParkingFacility stations**
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/ParkingFacility/?where=and(sorigin.eq.skidata,sactive.eq.true)
**ParkingStation stations**
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/ParkingStation/?where=and(sorigin.eq.skidata,sactive.eq.true)
**all stations**
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/*/?where=and(sorigin.eq.skidata,sactive.eq.true)
**data**
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/ParkingStation/*/latest?where=and(sorigin.eq.skidata,sactive.eq.true)

**Comment by rcavaliere** [comment]
That's fine, I will test it!

**Comment by rcavaliere** [comment]
@dulvui looks everything correctly implemented, cool!

One question: at present don't we receive any measurements for the ParkingFacility? Or better can't we calculate this based on the measurements associated to the child ParkingStations, as proposed in the specification document? And are you sure that we receive the free data types? Don't we receive information about occupied / reserved parking lots? Can you provide some examples of responses of their API?

Once this is clarified, the Data Collector can be considered "production ready". However, we have the open point related to the coordinates not present in the API. I got the feedback that they will extend the API, so let's wait for this, correct the Data Collector, test it quickly again before going into production.

**Comment by dulvui** [comment]
@rcavaliere The facility itself doesn't give any measurements data, but of course it could be calculated based on the data of the child stations. I'll add that now and add a sum off all categorires to the ParkingFacility station.

For the free/occupied data we actually receive both from the API.
`CurrentLevel` represents occupied and `FreePlaces` free. Currently I only consider free places, but I will add also occupied now. I have missed the part in the specification, about storing both free and occupied data. 

Here an example response:
```json
{
  "ContentEncoding": null,
  "ContentType": null,
  "Data": {
    "Status": "OK",
    "FreePlaces": [
      {
        "FacilityID": 608612,
        "FacilityDescription": "Mobilitätszentrum",
        "ParkNo": 0,
        "CountingCategoryNo": 1,
        "CountingCategory": "Sosta Breve",
        "FreeLimit": 217,
        "OccupancyLimit": 218,
        "CurrentLevel": 58,
        "Reservation": 0,
        "Capacity": 218,
        "FreePlaces": 160
      },
      {
        "FacilityID": 608612,
        "FacilityDescription": "Mobilitätszentrum",
        "ParkNo": 0,
        "CountingCategoryNo": 2,
        "CountingCategory": "Abbonati",
        "FreeLimit": 20,
        "OccupancyLimit": 21,
        "CurrentLevel": 2,
        "Reservation": 0,
        "Capacity": 21,
        "FreePlaces": 19
      },
      {
        "FacilityID": 608612,
        "FacilityDescription": "Mobilitätszentrum",
        "ParkNo": 0,
        "CountingCategoryNo": 3,
        "CountingCategory": "Totale",
        "FreeLimit": 237,
        "OccupancyLimit": 239,
        "CurrentLevel": 60,
        "Reservation": 0,
        "Capacity": 239,
        "FreePlaces": 179
      }
    ]
  },
  "JsonRequestBehavior": 0,
  "MaxJsonLength": null,
  "RecursionLimit": null
}
```

**Comment by rcavaliere** [comment]
@dulvui I will test this this afternoon. For the coordinates issue, they Data Provider will implement this, but we are waiting for feedback

**Comment by dulvui** [comment]
@rcavaliere I added now all types also to ParkingFacility by making the sum of the data provided by the single ParkingStations of a Parking Facility.
All stations (PatkingFacility and ParkingStation) have now occupied/free measurements for all types, does that solve the second point?

Here the API call with all data type names for ParkingFacilities that are available now:
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/ParkingFacility/*/latest?where=sorigin.eq.skidata&select=tname
And here of course all data
https://mobility.api.opendatahub.testingmachine.eu/v2/flat,node/ParkingFacility/*/latest?where=sorigin.eq.skidata

**Comment by rcavaliere** [comment]
@dulvui many thanks, now the integration seems to be perfect! Only one thing: why do we have two ParkingFacility stations and just one ParkingStation? Is exactly this that we get from the Data Provider?

**Comment by rcavaliere** [comment]
@dulvui perfect! Work is here is completed, please wait my input before deploy on production

**Comment by rcavaliere** [comment]
Skidata should have now fixed the coordinates issue. @dulvui, why don't we see the data on the testing version of analytics? If the coordinates were hardcoded, let's adapt the Data Collector so to read them from the API

**Comment by dulvui** [comment]
@rcavaliere You are right they are hardcoded, because I don't know the name of the location field yet.
But I still don't see any location in the data. Is there another call to make or a new endpoint?
Here the response:
```json
      {
        "IdCompany": 18,
        "FacilityId": 608612,
        "Description": "Parcheggio Stazione Brunico",
        "City": "Bolzano",
        "Address": "Via dei Conciapelli, 60",
        "ZIPCode": "39100",
        "Telephone1": null,
        "Telephone2": null,
        "PostNumber": 500,
        "ReceiptMerchant": "STA – Strutture Trasporto Alto Adige SpA Via dei Conciapelli, 60 39100  Bolzano UID: 00586190217",
        "Web": null
      },
      {
        "IdCompany": 19,
        "FacilityId": 607440,
        "Description": "Parcheggio Stazione Bressanone",
        "City": "Bressanone",
        "Address": "Via dei Conciapelli, 60",
        "ZIPCode": "39100",
        "Telephone1": null,
        "Telephone2": null,
        "PostNumber": 500,
        "ReceiptMerchant": "STA – Strutture Trasporto Alto Adige SpA Via dei Conciapelli, 60 39100  Bolzano UID: 00586190217",
        "Web": null
      },
```

**Comment by rcavaliere** [comment]
@dulvui thanks for the feedback, I will check with the Skidata supplier. Anyway, why is the data not visible on analytics.testingmachine.eu?

**Comment by rcavaliere** [comment]
@dulvui let's wait to have the contracts signed before publishing the Data Collector

**Comment by clezag** [comment]
@rcavaliere @dulvui I've noticed that currently the data collector fails because the request to the data provider does not return a JSON anymore, but a HTML login page instead.
The Authorization token has an invalid signature, but I don't know if that's the reason why, or if it's always like that.

Can you check with the provider?

**Comment by rcavaliere** [comment]
@clezag thanks for the information, I will take care of this!

**Comment by rcavaliere** [comment]
@clezag @dulvui we can release the new STA parking data in production, they would like to have it visible on parking.bz.it as soon as possible.

**Comment by dulvui** [comment]
@rcavaliere Okay I'll put into production now, but we still use the old API to get the data, is that okay?
I also just checked the new API, and there are still issues as before.

**Comment by dulvui** [comment]
@rcavaliere now it is live in production
https://mobility.api.opendatahub.com/v2/flat,node/ParkingFacility/*/latest?where=sorigin.eq.skidata

And visible on https://analytics.opendatahub.com/
![image](https://github.com/user-attachments/assets/404e9ffc-d8d9-445a-9225-9c37ab0353c0)

And on https://parking.opendatahub.com/
![image](https://github.com/user-attachments/assets/3af7a0e7-99ff-4379-9260-107bd84d281e)

**Comment by rcavaliere** [comment]
@dulvui nice! Can we have on parking.bz.it the views also for Bressanone and Brunico?

**Comment by sseppi** [comment]
@rcavaliere please let the customer care team know when the contract is signed, to publish the new dataset in the Data Browser and on the Open Data Hub Website

**Comment by rcavaliere** [comment]
@sseppi I will do, the contract is in signature process at STA!
