### ISSUE TITLE
Migrate all A22 Data Collectors to new A22 back-end end-point

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#678]
New end-point and credentials are the ones used to now connect the Data Collectors A22 Travel Times and Traffic, see #673 

Data collectors to be migrated:
- [x] VMS
- [x] Parking
- [x] RWIS
- [x] Events

**Comment by clezag** [comment]
Changes are up in testing. Will check logs in a day or so, when every scheduled task has been run

**Comment by clezag** [comment]
@rcavaliere I've checked the logs in testing, they all look fine and are getting data.

**Comment by rcavaliere** [comment]
@clezag wonderful, let's make the change at the beginning of next week

**Comment by clezag** [comment]
@rcavaliere all up and running
