### ISSUE TITLE
Carsharing halapi data collector not authenticated

### ISSUE THREAD

**Issue by clezag** [noi-techpark/bdp-commons#683]
Data collector carsharing-halapi throws errors due to missing authentication since 2024.10.16.

`
{\"faultCode\":\"Client.AccessDenied\",\"faultString\":\"AccessDenied Not authenticated\",\"detail\":[{\"errorCode\":17,\"errorText\":\"AccessDenied\",\"errorAddtext\":\"Not authenticated\"}]}
`

The most recent changes to this code, and deployments are from june 2024, so it's probable that the provider deactivated our user.

@rcavaliere I think we should reach out to the data provider and notify them of this issue

**Comment by rcavaliere** [comment]
@clezag as I told you this is because the old service has been shut down, we have a new technological back-end system to integrate - see #677. Therefore no action is going to take place here.
