### ISSUE TITLE
As the manager of the Digitalproject Tourism South Tyrol I would like to have an access to the Kibana dashboard to see the big data of the touristic content of the ODH.

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/bdp-commons#80]
- [x] @RudiThoeni sends a description of the fields in the logs to @niettadesantis 
- [ ] @niettadesantis will create some user stories
- [ ] we ask @alexlanz a evaluation of effort to build dashboards for the user stories identified by @niettadesantis

**Comment by RudiThoeni** [comment]
Description of the Logged Fields

The api logs all request that comes from
-suedtirol.info
-landingpages 
-suedtirol app
-Tourism data browser 

-Timestamp
-Requested URL on the api
-HTTP Method (GET POST PUT etc..)
-IP from where Request was made
-Username if available (for a logged app user, or elements if a request comes from suedtirol.info, marketingfactory for landingpages)
-User Agent (browser, server, Phone etc...)
-Status of the request (200 = ok. 400 = bad request)
-Time Taken for the request in milliseconds

**Comment by niettadesantis** [comment]
Don't seem to be priority of IDM at this moment. Will eventually create a new issue if it's needed.
