### ISSUE TITLE
As a traffic manager, I would like to have new link stations due to new Bluetooth box installations

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-commons#82]
Two new link stations have to be created, connecting TIS to via_Galilei_Virgolo (one for each direction).
We should also create two new link stations connecting Agip_Einstein (new box) to meinstein (one for each direction).

Moved from noi-techpark/bdp-bluetooth-vehicle-traffic

**Comment by Piiit** [comment]
@rcavaliere  Done... Please test!

**Comment by rcavaliere** [comment]
@Piiit where did you test this? I don't see the new link stations in the test DB.
