### ISSUE TITLE
Change end-point for APPATN AQ Data Collector

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#84]
New end-point (finally HTTPS):
https://api.appa.tn.it/brennerlec/

**Comment by rcavaliere** [comment]
New end-point (finally HTTPS):
https://api.appa.tn.it/brennerlec/

**Comment by rcavaliere** [comment]
@Piiit @bertolla the data from station 'BrennerLEC' seems to enter correctly in the testing environment.
Did you change something for the "APPATN open data" Data Collector? In this case the end-point must not be changed. I see that the open data stream is not up-to-date. Can you please check and let me know?

**Comment by Piiit** [comment]
@rcavaliere 
> Did you change something for the "APPATN open data" Data Collector? In this case the end-point must not be changed. I see that the open data stream is not up-to-date. Can you please check and let me know?

- Do you mean `data-collectors/environment-appa/appatn_opendata`? Can you please use the folder names inside bdp_commons to be clearer... thx :-)
- Can you explain this issue? As I understand it, `appatn_tenminutes` should get a new endpoint https://api.appa.tn.it/brennerlec/ and `appatn_opendata` should keep the old one (https://appa.alpz.it/aria/opendata/json/)?

I see, that inside the code nothing has been changed lately. However, both DCs still use an older version of the dc-interface. We could update it to 2.1.1 and deploy it again. I dunno if that makes a difference.

**Comment by rcavaliere** [comment]
@Piiit my answers:

- Yes, I mean the folder you mentioned
- Yes, you understood correctly


`

**Comment by Piiit** [comment]
@rcavaliere 
I tested both DCs. The endpoints are set as described above.
