### ISSUE TITLE
As a project manager, I would like that the car pooling DC is modified so to be integrated in the bdp-core v2.

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#89]
In this activity please also clean up all data related to car pooling stored in the DB, which is fake data.

**Comment by bertolla** [comment]
Hub synchronization sometimes does not work. Need to investigate further!

**Comment by bertolla** [comment]
Fixed the sync issues but needs further testing. I didn't have it again.

**Comment by ohnewein** [comment]
Still doesn't work
