### ISSUE TITLE
Move geoserver to a standalone server to allow horizontal scaling of webservices

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/bdp-commons#92]
- [x] setup a eb environment to host geoserver alone
- [x] test new geoserver version
- [ ] switch endpoint for geoserver
- [ ] remove old geoserver
- [ ] make ws load-balanced with multiple instances

**Comment by bertolla** [comment]
Please test if new geoserver is working correctly(credentials are the same)
http://odh-geoserver.eu-west-1.elasticbeanstalk.com/web/

**Comment by Piiit** [comment]
Tested edi:parking, edi:Carsharing and edi:Echarging with mobility.meran.eu --> OK
cleanroad-stations, bikesharing, carpooling, pollution* tested with the Geoserver Layer Preview --> OK
