### ISSUE TITLE
As a project manager, I would like to set up to CI pipeline for the A22 innovative AQ sensors DC developed by Nicola Pedot

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-commons#95]
- [x]  Nicola needs to make a pull request for the latest changes
- [x] CI pipeline for unit testing
- [x] test pipeline to deploy the app to the testserver
- [x] get credentials to access test environment

**Comment by bertolla** [comment]
Waiting for Nicola to solve merge conflict

**Comment by bertolla** [comment]
@rcavaliere Could you in the meanwhile provide me access to the test environment? Nicola told me it's in the documentation

**Comment by rcavaliere** [comment]
host: mqtt-test.algorab.net
Porta: 61619
Username: testMQTT
Password: testMQTT
